version: "3.0"
services:
  verdaccio:
    image: verdaccio/verdaccio
    ports:
    - "4873:4873"
    volumes:
    - ./conf:/verdaccio/conf
    - verdaccio_storage:/verdaccio/storage

volumes:
  verdaccio_storage:
    driver: local
