
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
steps:
- task: Cache@2
  displayName: Cache Yarn packages
  inputs:
    key: yarn | $(Agent.OS) | yarn.lock
    path: $(YARN_CACHE_FOLDER)
    restoreKeys: |
      yarn | $(Agent.OS)
      yarn
    cacheHitVar: CACHE_RESTORED
- script: |
    yarn --frozen-lockfile
  displayName: 'install dependencies'
- script: |
    yarn test
  displayName: 'run unit tests'
- script: |
    yarn build
  displayName: 'build'
- script: |
    yarn release
  env:
    GH_TOKEN: $(GH_TOKEN)
    NPM_TOKEN: $(NPM_TOKEN)
  displayName: 'create and release the package to github and npm'
