
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Install_Node
  displayName: 'Install Node.js and dependencies'
  variables:
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(YARN_CACHE_FOLDER)
  - script: yarn --frozen-lockfile

- job: test
  displayName: 'run unit tests'
  dependsOn: Install_Node
  steps:
  - script: yarn test

- job: build
  displayName: 'build package'
  dependsOn: test
  steps:
  - script: yarn build

- job: release
  displayName: 'release package'
  dependsOn: build
  steps:
    - script: yarn release
      env:
        GH_TOKEN: $(GH_TOKEN)
        NPM_TOKEN: $(NPM_TOKEN)
